# Generated by Django 2.2.13 on 2020-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_review',
            name='ratings',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_review',
            name='title',
            field=models.CharField(default='Good Stuff', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_review',
            name='ratings',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_review',
            name='title',
            field=models.CharField(default='Good Product', max_length=255),
            preserve_default=False,
        ),
    ]
