# Generated by Django 2.2.13 on 2020-09-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200912_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product_uuid',
        ),
    ]
