# Generated by Django 2.2.13 on 2020-09-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200912_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_uuid',
            new_name='id',
        ),
    ]
