# Generated by Django 2.2.13 on 2020-09-28 21:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200929_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
