# Generated by Django 2.2.13 on 2020-09-29 02:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200929_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
